sonar.projectKey=meet2pratik
sonar.organization=meet2pratik
sonar.host.url=https://sonarcloud.io
sonar.token=558a069315a173a384214851e135630deefcc8fd
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8