sonar.projectKey=meet2pratik_DevSecOps
sonar.organization=meet2pratik
sonar.host.url=https://sonarcloud.io
sonar.login=${6196d4da20043c01062e76db609d1fe332bc88f1}
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8